import { User } from '../types/user';

export const mockUsers: User[] = [
  // LEGENDARY - DARKNESS (Top 5)
  {
    id: '1',
    nickname: 'EmperorMax',
    rating: 9850,
    rank: 2,
    faction: 'darkness',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Max123',
    joinDate: '2024-01-15',
    purchases: 127,
    achievements: ['First Purchase', 'Top 10', 'Rank #2', 'Gold Tier'],
  },
  {
    id: '2',
    nickname: 'DarkLord',
    rating: 9650,
    rank: 3,
    faction: 'darkness',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Dark456',
    joinDate: '2024-01-18',
    purchases: 115,
    achievements: ['First Purchase', 'Top 10', 'Gold Tier'],
  },
  {
    id: '3',
    nickname: 'ShadowKing',
    rating: 9500,
    rank: 5,
    faction: 'darkness',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Shadow789',
    joinDate: '2024-01-22',
    purchases: 108,
    achievements: ['First Purchase', 'Top 10', 'Gold Tier'],
  },
  {
    id: '4',
    nickname: 'Nightfall',
    rating: 9400,
    rank: 7,
    faction: 'darkness',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Night101',
    joinDate: '2024-01-25',
    purchases: 102,
    achievements: ['First Purchase', 'Top 10'],
  },
  {
    id: '5',
    nickname: 'Raven',
    rating: 9300,
    rank: 9,
    faction: 'darkness',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Raven202',
    joinDate: '2024-01-28',
    purchases: 98,
    achievements: ['First Purchase', 'Top 10'],
  },

  // LEGENDARY - LIGHT (Top 5)
  {
    id: '6',
    nickname: 'LightBringer',
    rating: 9950,
    rank: 1,
    faction: 'light',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Light123',
    joinDate: '2024-01-16',
    purchases: 120,
    achievements: ['First Purchase', 'Top 10', 'Rank #1', 'Gold Tier'],
  },
  {
    id: '7',
    nickname: 'SunQueen',
    rating: 9600,
    rank: 4,
    faction: 'light',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Sun456',
    joinDate: '2024-01-19',
    purchases: 112,
    achievements: ['First Purchase', 'Top 10', 'Gold Tier'],
  },
  {
    id: '8',
    nickname: 'Radiance',
    rating: 9450,
    rank: 6,
    faction: 'light',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Radiance789',
    joinDate: '2024-01-23',
    purchases: 105,
    achievements: ['First Purchase', 'Top 10', 'Gold Tier'],
  },
  {
    id: '9',
    nickname: 'Dawn',
    rating: 9350,
    rank: 8,
    faction: 'light',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Dawn101',
    joinDate: '2024-01-26',
    purchases: 100,
    achievements: ['First Purchase', 'Top 10'],
  },
  {
    id: '10',
    nickname: 'Aurora',
    rating: 9250,
    rank: 10,
    faction: 'light',
    tier: 'legendary',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Aurora202',
    joinDate: '2024-01-29',
    purchases: 96,
    achievements: ['First Purchase', 'Top 10'],
  },

  // NOBLE CIRCLE - DARKNESS (20 members)
  {
    id: '11',
    nickname: 'WarriorX',
    rating: 8950,
    rank: 11,
    faction: 'darkness',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Warrior303',
    joinDate: '2024-02-01',
    purchases: 89,
    achievements: ['First Purchase'],
  },
  {
    id: '12',
    nickname: 'Venom',
    rating: 8850,
    rank: 12,
    faction: 'darkness',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Venom404',
    joinDate: '2024-02-03',
    purchases: 85,
    achievements: ['First Purchase'],
  },
  {
    id: '13',
    nickname: 'Eclipse',
    rating: 8750,
    rank: 13,
    faction: 'darkness',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Eclipse505',
    joinDate: '2024-02-05',
    purchases: 82,
    achievements: ['First Purchase'],
  },
  {
    id: '14',
    nickname: 'Phantom',
    rating: 8650,
    rank: 14,
    faction: 'darkness',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Phantom606',
    joinDate: '2024-02-07',
    purchases: 79,
    achievements: ['First Purchase'],
  },
  {
    id: '15',
    nickname: 'Obsidian',
    rating: 8550,
    rank: 15,
    faction: 'darkness',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Obsidian707',
    joinDate: '2024-02-09',
    purchases: 76,
    achievements: ['First Purchase'],
  },
  { id: '16', nickname: 'Reaper', rating: 8450, rank: 16, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Reaper808', joinDate: '2024-02-11', purchases: 73, achievements: ['First Purchase'] },
  { id: '17', nickname: 'Void', rating: 8350, rank: 17, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Void909', joinDate: '2024-02-13', purchases: 70, achievements: ['First Purchase'] },
  { id: '18', nickname: 'Abyss', rating: 8250, rank: 18, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Abyss1010', joinDate: '2024-02-15', purchases: 67, achievements: ['First Purchase'] },
  { id: '19', nickname: 'Dusk', rating: 8150, rank: 19, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Dusk1111', joinDate: '2024-02-17', purchases: 64, achievements: ['First Purchase'] },
  { id: '20', nickname: 'Onyx', rating: 8050, rank: 20, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Onyx1212', joinDate: '2024-02-19', purchases: 61, achievements: ['First Purchase'] },
  { id: '21', nickname: 'Chaos', rating: 7950, rank: 21, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Chaos1313', joinDate: '2024-02-21', purchases: 58, achievements: ['First Purchase'] },
  { id: '22', nickname: 'Wraith', rating: 7850, rank: 22, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Wraith1414', joinDate: '2024-02-23', purchases: 55, achievements: ['First Purchase'] },
  { id: '23', nickname: 'Gloom', rating: 7750, rank: 23, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Gloom1515', joinDate: '2024-02-25', purchases: 52, achievements: ['First Purchase'] },
  { id: '24', nickname: 'Noir', rating: 7650, rank: 24, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Noir1616', joinDate: '2024-02-27', purchases: 49, achievements: ['First Purchase'] },
  { id: '25', nickname: 'Umbra', rating: 7550, rank: 25, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Umbra1717', joinDate: '2024-03-01', purchases: 46, achievements: ['First Purchase'] },
  { id: '26', nickname: 'Cinder', rating: 7450, rank: 26, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Cinder1818', joinDate: '2024-03-03', purchases: 43, achievements: ['First Purchase'] },
  { id: '27', nickname: 'Rogue', rating: 7350, rank: 27, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Rogue1919', joinDate: '2024-03-05', purchases: 40, achievements: ['First Purchase'] },
  { id: '28', nickname: 'Sable', rating: 7250, rank: 28, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Sable2020', joinDate: '2024-03-07', purchases: 37, achievements: ['First Purchase'] },
  { id: '29', nickname: 'Grimm', rating: 7150, rank: 29, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Grimm2121', joinDate: '2024-03-09', purchases: 34, achievements: ['First Purchase'] },
  { id: '30', nickname: 'Vortex', rating: 7050, rank: 30, faction: 'darkness', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Vortex2222', joinDate: '2024-03-11', purchases: 31, achievements: ['First Purchase'] },

  // NOBLE CIRCLE - LIGHT (20 members)
  {
    id: '31',
    nickname: 'Celestial',
    rating: 8900,
    rank: 31,
    faction: 'light',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Celestial303',
    joinDate: '2024-02-02',
    purchases: 87,
    achievements: ['First Purchase'],
  },
  {
    id: '32',
    nickname: 'Divinity',
    rating: 8800,
    rank: 32,
    faction: 'light',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Divinity404',
    joinDate: '2024-02-04',
    purchases: 84,
    achievements: ['First Purchase'],
  },
  {
    id: '33',
    nickname: 'Seraph',
    rating: 8700,
    rank: 33,
    faction: 'light',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Seraph505',
    joinDate: '2024-02-06',
    purchases: 81,
    achievements: ['First Purchase'],
  },
  {
    id: '34',
    nickname: 'Glory',
    rating: 8600,
    rank: 34,
    faction: 'light',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Glory606',
    joinDate: '2024-02-08',
    purchases: 78,
    achievements: ['First Purchase'],
  },
  {
    id: '35',
    nickname: 'Beacon',
    rating: 8500,
    rank: 35,
    faction: 'light',
    tier: 'noble',
    avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Beacon707',
    joinDate: '2024-02-10',
    purchases: 75,
    achievements: ['First Purchase'],
  },
  { id: '36', nickname: 'Virtue', rating: 8400, rank: 36, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Virtue808', joinDate: '2024-02-12', purchases: 72, achievements: ['First Purchase'] },
  { id: '37', nickname: 'Haven', rating: 8300, rank: 37, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Haven909', joinDate: '2024-02-14', purchases: 69, achievements: ['First Purchase'] },
  { id: '38', nickname: 'Zenith', rating: 8200, rank: 38, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Zenith1010', joinDate: '2024-02-16', purchases: 66, achievements: ['First Purchase'] },
  { id: '39', nickname: 'Nova', rating: 8100, rank: 39, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Nova1111', joinDate: '2024-02-18', purchases: 63, achievements: ['First Purchase'] },
  { id: '40', nickname: 'Lumina', rating: 8000, rank: 40, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Lumina1212', joinDate: '2024-02-20', purchases: 60, achievements: ['First Purchase'] },
  { id: '41', nickname: 'Aether', rating: 7900, rank: 41, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Aether1313', joinDate: '2024-02-22', purchases: 57, achievements: ['First Purchase'] },
  { id: '42', nickname: 'Solstice', rating: 7800, rank: 42, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Solstice1414', joinDate: '2024-02-24', purchases: 54, achievements: ['First Purchase'] },
  { id: '43', nickname: 'Halo', rating: 7700, rank: 43, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Halo1515', joinDate: '2024-02-26', purchases: 51, achievements: ['First Purchase'] },
  { id: '44', nickname: 'Opal', rating: 7600, rank: 44, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Opal1616', joinDate: '2024-02-28', purchases: 48, achievements: ['First Purchase'] },
  { id: '45', nickname: 'Ivory', rating: 7500, rank: 45, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Ivory1717', joinDate: '2024-03-02', purchases: 45, achievements: ['First Purchase'] },
  { id: '46', nickname: 'Pearl', rating: 7400, rank: 46, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Pearl1818', joinDate: '2024-03-04', purchases: 42, achievements: ['First Purchase'] },
  { id: '47', nickname: 'Prism', rating: 7300, rank: 47, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Prism1919', joinDate: '2024-03-06', purchases: 39, achievements: ['First Purchase'] },
  { id: '48', nickname: 'Spark', rating: 7200, rank: 48, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Spark2020', joinDate: '2024-03-08', purchases: 36, achievements: ['First Purchase'] },
  { id: '49', nickname: 'Shimmer', rating: 7100, rank: 49, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Shimmer2121', joinDate: '2024-03-10', purchases: 33, achievements: ['First Purchase'] },
  { id: '50', nickname: 'Flare', rating: 7000, rank: 50, faction: 'light', tier: 'noble', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Flare2222', joinDate: '2024-03-12', purchases: 30, achievements: ['First Purchase'] },

  // TREASURE HUNTERS - DARKNESS (All others)
  { id: '51', nickname: 'HunterD1', rating: 6900, rank: 51, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter2323', joinDate: '2024-03-14', purchases: 28, achievements: ['First Purchase'] },
  { id: '52', nickname: 'HunterD2', rating: 6800, rank: 52, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter2424', joinDate: '2024-03-16', purchases: 26, achievements: ['First Purchase'] },
  { id: '53', nickname: 'HunterD3', rating: 6700, rank: 53, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter2525', joinDate: '2024-03-18', purchases: 24, achievements: ['First Purchase'] },
  { id: '54', nickname: 'HunterD4', rating: 6600, rank: 54, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter2626', joinDate: '2024-03-20', purchases: 22, achievements: ['First Purchase'] },
  { id: '55', nickname: 'HunterD5', rating: 6500, rank: 55, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter2727', joinDate: '2024-03-22', purchases: 20, achievements: ['First Purchase'] },
  { id: '56', nickname: 'HunterD6', rating: 6400, rank: 56, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter2828', joinDate: '2024-03-24', purchases: 18, achievements: ['First Purchase'] },
  { id: '57', nickname: 'HunterD7', rating: 6300, rank: 57, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter2929', joinDate: '2024-03-26', purchases: 16, achievements: ['First Purchase'] },
  { id: '58', nickname: 'HunterD8', rating: 6200, rank: 58, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter3030', joinDate: '2024-03-28', purchases: 14, achievements: ['First Purchase'] },
  { id: '59', nickname: 'HunterD9', rating: 6100, rank: 59, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter3131', joinDate: '2024-03-30', purchases: 12, achievements: ['First Purchase'] },
  { id: '60', nickname: 'HunterD10', rating: 6000, rank: 60, faction: 'darkness', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Hunter3232', joinDate: '2024-04-01', purchases: 10, achievements: ['First Purchase'] },

  // TREASURE HUNTERS - LIGHT (All others)
  { id: '61', nickname: 'HunterL1', rating: 6850, rank: 61, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL2323', joinDate: '2024-03-15', purchases: 27, achievements: ['First Purchase'] },
  { id: '62', nickname: 'HunterL2', rating: 6750, rank: 62, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL2424', joinDate: '2024-03-17', purchases: 25, achievements: ['First Purchase'] },
  { id: '63', nickname: 'HunterL3', rating: 6650, rank: 63, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL2525', joinDate: '2024-03-19', purchases: 23, achievements: ['First Purchase'] },
  { id: '64', nickname: 'HunterL4', rating: 6550, rank: 64, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL2626', joinDate: '2024-03-21', purchases: 21, achievements: ['First Purchase'] },
  { id: '65', nickname: 'HunterL5', rating: 6450, rank: 65, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL2727', joinDate: '2024-03-23', purchases: 19, achievements: ['First Purchase'] },
  { id: '66', nickname: 'HunterL6', rating: 6350, rank: 66, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL2828', joinDate: '2024-03-25', purchases: 17, achievements: ['First Purchase'] },
  { id: '67', nickname: 'HunterL7', rating: 6250, rank: 67, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL2929', joinDate: '2024-03-27', purchases: 15, achievements: ['First Purchase'] },
  { id: '68', nickname: 'HunterL8', rating: 6150, rank: 68, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL3030', joinDate: '2024-03-29', purchases: 13, achievements: ['First Purchase'] },
  { id: '69', nickname: 'HunterL9', rating: 6050, rank: 69, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL3131', joinDate: '2024-03-31', purchases: 11, achievements: ['First Purchase'] },
  { id: '70', nickname: 'HunterL10', rating: 5950, rank: 70, faction: 'light', tier: 'treasure', avatar: 'https://api.dicebear.com/7.x/adventurer/svg?seed=HunterL3232', joinDate: '2024-04-02', purchases: 9, achievements: ['First Purchase'] },
];
